CREATE TABLE TB_TASK(
 CD_TASK INTEGER NOT NULL,
 DESCRICAO_TASK VARCHAR(120) NOT NULL,
 TITULO_TASK VARCHAR(120) NOT NULL,
 STATUS_TASK VARCHAR(60) NOT NULL,
 DT_CRIACAO_TASK DATE NOT NULL,
 DT_REMOCAO_TASK DATE,
 DT_EDICAO_TASK DATE,
 DT_CONCLUSAO_TASK DATE,
 CD_USUARIO INTEGER,
 CONSTRAINT PK_CD_TASK PRIMARY KEY(CD_TASK),
 CONSTRAINT FK_CD_USUARIO FOREIGN KEY(CD_USUARIO) REFERENCES TB_USUARIO(CD_USUARIO) 
);

CREATE SEQUENCE SEQ_TASK
START WITH 1
MINVALUE 1
MAXVALUE 99999
NOCACHE
NOCYCLE;